### PR TITLE
Started writing docs for getting spaCy NER running

### LINKED ISSUE #150: ner_daemon_spacy.py doesn't work out of the box
This is what you get running python 3.9 on the nlp dir script `ner_daemon_spacy.py`

If there is a prestep to running this script then we need to document it and/or script it in the .py file instead

```
thomas@thomas-CF-31WBLAHLM:~/IsIdentifiable/nlp$ python3 ./ner_daemon_spacy.py 
Traceback (most recent call last):
  File "./ner_daemon_spacy.py", line 43, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ner_daemon_spacy.py", line 45, in <module>
    raise Exception("Cannot load SpaCy module, try source $SMI_ROOT/lib/python3/virtualenvs/spacy2/$(hostname -s)/bin/activate")
Exception: Cannot load SpaCy module, try source $SMI_ROOT/lib/python3/virtualenvs/spacy2/$(hostname -s)/bin/activate

```

### LINKED ISSUE #156: Update `test_ner_daemon_spacy.py` to be less strict
Given the vagaries of different versions of spaCy and or the language file user has chosen.  We should update the `test_ner_daemon_spacy.py` to be less strict.

We should provide a longer input string and only require that a few things are classified. 

The purpose of this script should be to check that the service is running and is returning 'something sensible'.  We don't need an assert for specific words (at least in this repository -  we might want stricter tests elsewhere e.g. in SmiServices).

### PR DESCRIPTION
**Pull request by tznind**
Fixes #150 
Fixes #156

This is a work in progress, still trying to figure out what pip commands are needed to make this thing work

### CODE REVIEW

**Comment by tznind** [comment]
Ok I've run the following steps 

- [ ] sudo apt-get install python3.9
- [ ] pip install -U spacy
- [ ] pip install -U scispacy
- [ ] python3 -m spacy download en_core_web_sm

and now get

```
thomas@thomas-CF-31WBLAHLM:~/IsIdentifiable/nlp$ python3 ./ner_daemon_spacy.py 
Logging to None
Traceback (most recent call last):
  File "./ner_daemon_spacy.py", line 229, in <module>
    ThreadedServer(bindip, port_num, spacy_model_list = spacy_models).run()
  File "./ner_daemon_spacy.py", line 152, in __init__
    self.nlp_list.append( spacy.load(model, disable=["tagger", "parser"]) )
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/home/thomas/.local/lib/python3.8/site-packages/spacy/util.py", line 427, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.
```

@jas88  or @howff  got any hints? I would like to document the minimum commands to make it work (what to install) so if any of the above commands are wrong or not needed let me know and I will remove them.

**Comment by howff** [comment]
You have downloaded `en_core_web_sm` but the error message is referring to `en_core_web_md` (small vs medium size model, respectively).

**Comment by howff** [comment]
The SmiServices python common library has a requirements.txt which installs the necessary packages, so having a virtual environment with SmiServices installed should be sufficient. (Although I can't remember right now how or if that handles the SpaCy language model)

**Comment by howff** [comment]
* in my tests you also need to `pip install pyyaml`
* the warning about the lemmatizer can be silenced by adding lemmatizer into the `disable=` line https://github.com/SMI/IsIdentifiable/blob/cfd5c586b36eb70f18e22b3a7509dd962e8436f1/nlp/ner_daemon_spacy.py#L152 so it looks like this: `disable=["tagger", "parser", "lemmatizer"]`
* the assertion error should print out the expected response and the actual response so you can see what went wrong (or maybe I am misremembering because that's what the python testing framework does)
* the assertion error is telling you that spacy didn't return the expected PII. You can `print(response)` to see what's coming back. In one case I found that `PERSON` should be `ORGANIZATION` which is fine, just change the assert and it will pass. But the big problem is that `pip install spacy` now installs SpaCy version 3, whereas the software was developed with SpaCy version 2. Version 3 is only spotting the date "today" not the names. If you `pip install -U spacy==2.3.7` then you get the expected results. At this moment in time I'm not sure whether to conclude that spacy v3 is bad, or the test case is bad, or whether we can say anything at all about how well it will perform on the particular data we have in the safe haven.
* I tested `_sm` and `_md` models in v3 and got the same result.

**Review by jas88 — APPROVED** [review]

**Pull request merged**
