### PR TITLE
Fixed nuget package assets

### PR DESCRIPTION
**Pull request by tznind**

### CODE REVIEW

**Review by jas88 — APPROVED** [review]

**Comment by tznind** [comment]
Ignore that CI message about spaCy was on a stale branch

**Comment by tznind** [comment]
Hmn our ci package command is 

` dotnet pack NuGet/IsIdentifiable.NuGet.csproj -c Release --include-source --include-symbols --nologo -p:NuspecFile=`pwd`/NuGet/IsIdentifiable.NuGet.nuspec -p:NuspecProperties=Version=$(fgrep AssemblyInformationalVersion SharedAssemblyInfo.cs|cut -d'"' -f2)\;configuration=Release  -p:SymbolPackageFormat=snupkg`

that makes me wonder if we need that assets path in there too

**Comment by jas88** [comment]
Just run `./ner_daemon_spacy.py -d en_core_web_md` (at least on a branch that has -d implemented) and it'll download the missing en_core_web_md file for you, or grab it manually from https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.4.0/en_core_web_md-3.4.0-py3-none-any.whl and put it ... wherever it is spaCy expects it installed. (I have no idea about Python packaging, but apparently that's a "wheel" file with Python bits in, maybe comparable to a .nupkg?) There's documentation about it in spaCy's docs somewhere.

**Comment by jas88** [comment]
> I think if we can get #113 working (build from csproj and scrap teh NuGet project/nuspec that would be preferrable.

I'll rebuild #113 and get it working+merged properly next.

**Comment by tznind** [comment]
Need to prioritise this if possible.  I don't like having missing dlls in a new release.  0.0.5 doesn't even seem to have `libleptonica` in it at all so users can't even apply the manual copying workaround.

**Pull request merged**
